### ISSUE TITLE
Permissions

### ISSUE THREAD

**Issue by iverasp** [Webrewthebestbeer1/BlueTherm#1]
Need to check and ask for permissions at runtime

**Comment by iverasp** [comment]
`W/Binder: Caught a RuntimeException from the binder stub implementation.
                                                             java.lang.SecurityException: Need ACCESS_COARSE_LOCATION or ACCESS_FINE_LOCATION permission to get scan results
                                                                 at android.os.Parcel.readException(Parcel.java:1620)
                                                                 at android.os.Parcel.readException(Parcel.java:1573)
                                                                 at android.bluetooth.IBluetoothGatt$Stub$Proxy.startScan(IBluetoothGatt.java:772)
                                                                 at android.bluetooth.le.BluetoothLeScanner$BleScanCallbackWrapper.onClientRegistered(BluetoothLeScanner.java:324)
                                                                 at android.bluetooth.IBluetoothGattCallback$Stub.onTransact(IBluetoothGattCallback.java:56)
                                                                 at android.os.Binder.execTransact(Binder.java:453)`
